//! R3-A RED-PHASE proptest pin: did:key round-trip byte identity
//! (G14-A1, plan §4 seed).
//!
//! Pin source: r2-test-landscape §2.2 G14-A1 row
//! `prop_did_key_round_trip_byte_identity`.
//!
//! ## Property under test
//!
//! For any 32-byte Ed25519 public key, the round-trip
//!
//! ```text
//! pubkey -> Did::from_public_key -> Did::resolve_to_public_key -> pubkey'
//! ```
//!
//! must satisfy `pubkey == pubkey'` byte-for-byte. This is a fundamental
//! correctness property of the multibase + multicodec encoding scheme:
//! NO bit can be silently dropped or rewritten by the encode → decode path.

#![allow(
    clippy::unwrap_used,
    clippy::used_underscore_binding,
    unreachable_code,
    reason = "RED-PHASE proptest stubs; G14-A1 implementer wires real bodies + drops these allows"
)]

use proptest::prelude::*;

proptest! {
    #![proptest_config(ProptestConfig::with_cases(10_000))]

    #[test]
    #[ignore = "RED-PHASE: G14-A1 wave-4a fills benten-id::did + Did::from_public_key + Did::resolve_to_public_key"]
    fn prop_did_key_round_trip_byte_identity(pubkey_bytes in any::<[u8; 32]>()) {
        // G14-A1 implementer wires this:
        //   let pk = benten_id::keypair::PublicKey::from_bytes(&pubkey_bytes).unwrap();
        //   let did = benten_id::did::Did::from_public_key(&pk);
        //   let pk_decoded = did.resolve_to_public_key().unwrap();
        //   prop_assert_eq!(pk_decoded.to_bytes(), pubkey_bytes,
        //       "did:key round-trip must preserve every bit of the public key");
        //
        // OBSERVABLE consequence across 10 000 cases of arbitrary
        // 32-byte sequences: encode → decode is byte-identity for all
        // public keys (not just for keys generated by `Keypair::generate`,
        // because an attacker / future protocol may craft DIDs from
        // arbitrary 32-byte values).
        let _ = pubkey_bytes;
        unimplemented!("G14-A1 wires did:key encode-decode byte-identity proptest");
    }
}
