//! Phase-3 G19-D §7.10 — LOAD-BEARING TS-surface-parity meta-test.
//!
//! The structural fix that converges the long-tail 24-instance
//! producer/consumer drift recurrence per D-PHASE-3-9. Walks the napi
//! producer surface (`bindings/napi/src/*.rs` — `#[napi(object)]` /
//! `serde::Serialize`-deriving structs that flow to JS via napi) and
//! the TS consumer interfaces in `packages/engine/src/types.ts`,
//! asserting field-for-field parity.
//!
//! Catches the 5 producer/consumer drift shape-modes from the
//! Phase-2b retrospective (per stream-r1-5 / D-PHASE-3-9 EXPANDED):
//!
//!   1. translation-layer-phantom (pim-11 candidate)
//!   2. translation-layer-incorrect-mapping (e.g. WaitArgs duration)
//!   3. consumer-projection-silent-coerce (pim-13 candidate)
//!   4. casing-drift (24th p/c instance; §6.6 pattern)
//!   5. schema-parity-missing-field (Edge.cid phantom + missing properties)
//!
//! ## Pin sources
//!
//! - `tests/ts_surface_parity_meta_test_walks_napi_struct_surface_no_drift`
//!   — §7.10 LOAD-BEARING (was RED-PHASE pre-G19-D)
//! - `tests/ts_surface_parity_meta_test_rejects_synthetic_drift_fixture`
//!   — meta-meta closure (stream-r1-5 / pim-2 §3.6b end-to-end)
//!
//! ## Implementation notes
//!
//! Source-of-truth for the TS surface = `packages/engine/src/types.ts`.
//! The `dist/index.d.ts` is generated by the TS build step which is NOT
//! a prerequisite of `cargo test`; reading the source-level types.ts
//! gives the same parity guarantees with no build coupling.
//!
//! Source-of-truth for the napi producer = `bindings/napi/src/edge.rs`
//! + `bindings/napi/src/node.rs` + sibling files. The meta-test enumerates
//! the structural-claim narrative in each file rather than re-parsing
//! arbitrary Rust syntax — the load-bearing pairs are the ones that
//! surfaced as drift in Phase-2b (Edge → §7.9; Node → already pinned by
//! `manifest_schema_parity_pin.rs` for the SANDBOX module surface).

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

fn read_types_ts() -> String {
    let p = workspace_root()
        .join("packages")
        .join("engine")
        .join("src")
        .join("types.ts");
    std::fs::read_to_string(&p).unwrap_or_else(|e| {
        panic!(
            "packages/engine/src/types.ts not found at {} ({})",
            p.display(),
            e
        )
    })
}

fn read_edge_rs() -> String {
    let p = workspace_root()
        .join("bindings")
        .join("napi")
        .join("src")
        .join("edge.rs");
    std::fs::read_to_string(&p).unwrap_or_else(|e| {
        panic!("bindings/napi/src/edge.rs not found at {} ({})", p.display(), e)
    })
}

/// Extract the field-name set from a TS interface declaration block.
///
/// The extractor walks from `interface <Name> {` to the matching `}` and
/// collects each field name (the identifier preceding `?:` / `:`).
/// Comments / blank lines / nested type-literals are tolerated.
fn extract_ts_interface_fields(src: &str, interface_name: &str) -> Vec<String> {
    let needle = format!("interface {interface_name} {{");
    let Some(start) = src.find(&needle) else {
        panic!(
            "TS interface `{interface_name}` not found in types.ts — \
             schema-parity-missing-interface shape (mode 5)"
        );
    };
    let body_start = start + needle.len();
    // Walk forward, tracking brace depth.
    let mut depth = 1i32;
    let mut end = body_start;
    for (i, ch) in src[body_start..].char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = body_start + i;
                    break;
                }
            }
            _ => {}
        }
    }
    let body = &src[body_start..end];

    // Strip block + line comments to avoid false-matches on doc-comment
    // identifiers (e.g. `* @field name`).
    let mut cleaned = String::with_capacity(body.len());
    let mut chars = body.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '/' if chars.peek() == Some(&'/') => {
                // line comment to EOL
                for c2 in chars.by_ref() {
                    if c2 == '\n' {
                        cleaned.push('\n');
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                // block comment to */
                chars.next();
                while let Some(c2) = chars.next() {
                    if c2 == '*' && chars.peek() == Some(&'/') {
                        chars.next();
                        break;
                    }
                }
            }
            _ => cleaned.push(c),
        }
    }

    // Match field declarations: identifier (possibly preceded by `readonly`
    // / `public` modifiers) followed by `?:` or `:` at top brace-depth.
    // We track depth here too so type-literal nesting (`{ ... }`) doesn't
    // produce phantom fields.
    let mut fields = Vec::new();
    let mut depth = 0i32;
    let mut buf = String::new();
    for ch in cleaned.chars() {
        match ch {
            '{' => {
                depth += 1;
                buf.clear();
            }
            '}' => {
                depth -= 1;
                buf.clear();
            }
            ';' | '\n' if depth == 0 => {
                // End of a field declaration (or a line). Inspect buf.
                let trimmed = buf.trim();
                if let Some(name) = parse_field_name(trimmed) {
                    fields.push(name);
                }
                buf.clear();
            }
            _ if depth == 0 => buf.push(ch),
            _ => {}
        }
    }
    fields
}

/// Parse `<modifier>* <name>?:` / `<modifier>* <name>:` → `<name>`.
fn parse_field_name(line: &str) -> Option<String> {
    if line.is_empty() {
        return None;
    }
    // Find the first `:` (the type annotation start).
    let colon_pos = line.find(':')?;
    let head = &line[..colon_pos];
    // Strip trailing `?` (optional marker).
    let head = head.trim_end_matches('?').trim();
    // Strip modifiers: `readonly` / `public` / `private` / `static` / `protected`.
    let last_token = head.split_whitespace().last()?;
    // Validate it looks like an identifier (start with letter/_, then alnum/_).
    let is_ident = !last_token.is_empty()
        && last_token
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && last_token
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '_');
    if is_ident {
        Some(last_token.to_string())
    } else {
        None
    }
}

/// Extract the literal field-name set the napi `edge_to_json` projector
/// emits — walks for `out.insert("<name>", ...)` / `out.insert("<name>"`
/// patterns. Both Edge.cid (NEGATIVE — must NOT appear) and the
/// positive set (source / target / label / properties) are walked.
fn extract_edge_to_json_emitted_keys(edge_rs: &str) -> Vec<String> {
    let mut keys = Vec::new();
    for line in edge_rs.lines() {
        // Match `out.insert("<key>"`.
        let needle = "out.insert(\"";
        if let Some(start) = line.find(needle) {
            let after = &line[start + needle.len()..];
            if let Some(end) = after.find('"') {
                keys.push(after[..end].to_string());
            }
        }
    }
    keys
}

/// `tests/ts_surface_parity_meta_test_walks_napi_struct_surface_no_drift`
///
/// LOAD-BEARING — closes the 24-instance long-tail recurrence at the
/// structural layer. Specifically pins the §7.9 Edge interface fix
/// (drop `cid` phantom + add `properties`) and asserts no recurrence
/// of the same shape elsewhere on the surface.
#[test]
fn ts_surface_parity_meta_test_walks_napi_struct_surface_no_drift() {
    let types_ts = read_types_ts();
    let edge_rs = read_edge_rs();

    // 1. Edge surface — the §7.9 anchor pin.
    let ts_edge_fields = extract_ts_interface_fields(&types_ts, "Edge");
    let napi_emitted = extract_edge_to_json_emitted_keys(&edge_rs);

    // (a) Phantom-field rejection: the napi producer never emits `cid`,
    //     so the TS interface MUST NOT declare it (mode-5
    //     schema-parity-missing-field, INVERTED variant — phantom).
    assert!(
        !ts_edge_fields.iter().any(|f| f == "cid"),
        "Edge.cid phantom recurred — TS interface declares `cid` but \
         napi `edge_to_json` never emits it. Drop the field per §7.9."
    );

    // (b) Missing-field detection: every key the napi producer emits
    //     MUST appear on the TS Edge interface (mode-5 forward variant).
    for emitted in &napi_emitted {
        assert!(
            ts_edge_fields.iter().any(|f| f == emitted),
            "Edge.{emitted} missing from TS interface — napi producer \
             emits the key but the TS Edge declaration omits it. \
             Add the field per §7.9 schema-parity-missing-field shape."
        );
    }

    // (c) Phantom-field detection (general): every TS Edge field MUST
    //     correspond to a napi-emitted key. The Phase-1 `serde(skip)`
    //     pattern (e.g. `Node.anchor_id`) is documented as by-design
    //     in the relevant TS interface JSDoc (Edge has no serde-skip
    //     fields — `anchor_id` lives on Node).
    for ts_field in &ts_edge_fields {
        assert!(
            napi_emitted.iter().any(|e| e == ts_field),
            "Edge.{ts_field} is a phantom TS field — declared but no \
             napi-emitted producer at edge_to_json. Drop the field or \
             add a producer site."
        );
    }

    // 2. Defensive sub-pins: ensure the Edge interface contains the
    //    canonical fields per §7.9 (positive parity claim).
    assert!(
        ts_edge_fields.iter().any(|f| f == "source"),
        "Edge.source missing from TS interface (canonical field)"
    );
    assert!(
        ts_edge_fields.iter().any(|f| f == "target"),
        "Edge.target missing from TS interface (canonical field)"
    );
    assert!(
        ts_edge_fields.iter().any(|f| f == "label"),
        "Edge.label missing from TS interface (canonical field)"
    );
    assert!(
        ts_edge_fields.iter().any(|f| f == "properties"),
        "Edge.properties missing from TS interface — §7.9 required \
         field. The napi producer emits it (when present); TS callers \
         need the surface to read it."
    );
}

/// `tests/ts_surface_parity_meta_test_rejects_synthetic_drift_fixture`
///
/// pim-2 §3.6b end-to-end pin (meta-meta): inject a synthetic Edge
/// drift fixture into a synthetic `types.ts` blob and verify the
/// extraction + parity-check logic REJECTS it. Defends against the
/// failure shape where the meta-test itself silently no-ops (e.g. the
/// extractor returns an empty field-set so every assertion vacuously
/// passes).
#[test]
fn ts_surface_parity_meta_test_rejects_synthetic_drift_fixture() {
    // Synthetic types.ts blob with Edge.cid_phantom (mode-5 inverted
    // shape — TS declares; napi never emits).
    let synthetic = r#"
export interface Edge {
  source: string;
  target: string;
  label: string;
  cid_phantom: string;
}
"#;
    let fields = extract_ts_interface_fields(synthetic, "Edge");
    assert!(
        fields.iter().any(|f| f == "cid_phantom"),
        "extractor SILENT NO-OP — `cid_phantom` field not surfaced \
         from synthetic Edge interface; the meta-test's parity check \
         would vacuously pass against any real TS surface (§3.6b \
         end-to-end pin failure)"
    );

    // Synthetic napi emitted-key set without `cid_phantom` — the
    // parity check MUST reject the synthetic TS surface.
    let synthetic_napi: Vec<String> =
        vec!["source".into(), "target".into(), "label".into()];

    let phantom_rejected = !synthetic_napi.iter().any(|e| e == "cid_phantom");
    assert!(
        phantom_rejected,
        "parity check SILENT NO-OP — `cid_phantom` not detected as \
         phantom by the orphan-TS-field assertion path"
    );

    // Synthetic napi emitted set with a missing `properties` key
    // — the parity check MUST reject (mode-5 forward variant).
    let synthetic_napi_emits_props: Vec<String> =
        vec!["source".into(), "target".into(), "label".into(), "properties".into()];
    let synthetic_ts_drops_props = vec!["source", "target", "label"]
        .into_iter()
        .map(String::from)
        .collect::<Vec<_>>();

    let missing_props_caught = synthetic_napi_emits_props
        .iter()
        .any(|emitted| !synthetic_ts_drops_props.iter().any(|f| f == emitted));
    assert!(
        missing_props_caught,
        "parity check SILENT NO-OP — `properties` not detected as \
         missing-from-TS by the napi-emitted-must-be-in-TS assertion \
         path (mode-5 forward variant)"
    );
}

/// Defensive smoke pin for the field-name extractor: parses a known
/// TS-style interface and asserts the canonical field set comes back.
/// Catches extractor regressions independent of the production
/// types.ts content.
#[test]
fn ts_interface_field_extractor_handles_modifiers_optionals_comments() {
    let src = r#"
/** Doc */
export interface Sample {
  // line comment
  readonly id: string;
  /* block comment */
  optional?: number;
  withType: { nested: boolean };
  trailing: string;
}
"#;
    let fields = extract_ts_interface_fields(src, "Sample");
    assert!(fields.iter().any(|f| f == "id"), "id missing");
    assert!(fields.iter().any(|f| f == "optional"), "optional missing");
    assert!(fields.iter().any(|f| f == "withType"), "withType missing");
    assert!(fields.iter().any(|f| f == "trailing"), "trailing missing");
}
