// Phase-4-Meta-Core — R3-W5 — TF-G-CORE-10 / #1204 — `index.d.ts`
// TS-side public-API parity gate. The R2 §2 G-CORE-10 (P-4) row +
// plan §1.A.FROZEN item 10 (the JS analog of cargo-public-api).
//
// ============================================================================
// RED-PHASE STATUS
// ============================================================================
//
//   >>> UN-SKIP AT: G-CORE-10 (PR-B #1203 lands; #1204 regenerated
//   `index.d.ts` lands; the parity-gate workflow is COMMITTED at
//   G-CORE-10 per plan §1.A.FROZEN item 10 three-stage placement:
//   BUILT in G-CORE-10, COMMITTED/FREEZE-FLIPPED in G-CORE-9, EXECUTING
//   in the §4 CI lane). The freeze-time enforcement half (drift =
//   CI red) is asserted at the partner pin
//   `bindings/napi/test/tf12_js_public_api_parity_gate_freeze.test.ts`.
//   §3.6e — closing-wave checklist un-skips; reviewer verifies landing.
//
// Disjointness vs `test/tf12_js_public_api_parity_gate_freeze.test.ts`
// (HARD — §3.5i): that file asserts the FREEZE PROPERTY (gate is
// promoted to deny-on-drift at G-CORE-9; PQ-hybrid-capable shape; no
// hardcoded Ed25519 32/64). THIS file asserts the G-CORE-10 BUILT
// stage: the regenerated `index.d.ts` reflects the PR-B `next()`
// sync→async break AND the §3.5g cross-language types.ts mirror is
// atomically updated in the SAME PR.
//
// ============================================================================
// GROUND-TRUTH (synced HEAD c9c11c56)
// ============================================================================
//
//   `bindings/napi/index.d.ts` exists at HEAD; was regenerated by
//   napi-rs CLI from the `#[napi]` Rust surface (current sync next()).
//   `packages/engine/src/types.ts` contains the consumer-facing
//   StreamHandle / Atrium types. PR-B's `StreamHandle.next()`
//   sync→async break must reflect in BOTH atomically (§3.5g
//   cross-language rule-mirror). Pre-PR-B: index.d.ts says
//   `next(): Buffer | null` (SYNC). Post-PR-B: index.d.ts must say
//   `next(): Promise<Buffer | null>` (or napi-rs AsyncTask Promise
//   shape) AND types.ts must mirror.
//
// ============================================================================
// §3.6g LITERAL discipline checklist
// ============================================================================
//
//  1. §3.5b HARDENED — README/INTERNALS.md/types.ts/index.d.ts swept.
//  2. §3.6b sub-rule 4 — SPECIFIC arm: post-PR-B index.d.ts reflects
//     next() Promise shape AND types.ts mirrors (§3.5g);
//     OBSERVABLE = the Promise/async return-type marker appears in the
//     `.d.ts` text; WOULD-FAIL if PR-B lands but index.d.ts forgets to
//     regenerate (the exact #1204 failure class).
//  3. §3.6e — RED-PHASE; un-skip = G-CORE-10.
//  4. §3.6f (pim-18) — production-arm: this scans the real
//     index.d.ts file on disk + the real types.ts; substantive content
//     check, not a constructibility assertion.
//  5. §3.5g (CRITICAL on this pin) — the WHOLE point is the Rust ↔ TS
//     atomic update; this pin enforces it.
//  6. §3.13 — per-test locals; no shared static.
//  7. §3.5n — R3-W5 verified pre-existing index.d.ts says `Buffer | null`
//     (SYNC) at HEAD before writing.
//
// Pin source: R2-test-landscape.md §2 G-CORE-10 (P-4) row + plan
// §1.A.FROZEN item 10 (#1204 parity gate) + §3.5g cross-language
// rule-mirror.

import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// __tests__/ is sibling of test/ at bindings/napi/__tests__; workspace
// root is three levels up.
const WORKSPACE_ROOT = resolve(HERE, "..", "..", "..");

function readWorkspaceFile(rel: string): string | null {
    const p = resolve(WORKSPACE_ROOT, rel);
    if (!existsSync(p)) return null;
    return readFileSync(p, "utf-8");
}

describe.skip(
    "TF-G-CORE-10 / R3-W5 #1204 index.d.ts ↔ types.ts atomic-mirror at G-CORE-10 (RED until PR-B + #1204 regen land together)",
    () => {
        it("post-PR-B index.d.ts reflects StreamHandle.next() Promise shape (would-FAIL if PR-B lands but #1204 regen does not)", () => {
            const dts = readWorkspaceFile("bindings/napi/index.d.ts");
            expect(
                dts,
                "bindings/napi/index.d.ts must exist (it is committed at HEAD per napi-rs convention)",
            ).not.toBeNull();

            // The shape signal we assert: post-PR-B the next() method on
            // the StreamHandle class signature is Promise-returning. We
            // do NOT lock a particular Promise-rendering (napi-rs may
            // emit `Promise<Buffer | null>` directly or via AsyncTask
            // shape); we assert the `next()` method's return type
            // contains "Promise" in the .d.ts text.
            const dtsText = dts!;
            const streamHandleStart = dtsText.indexOf(
                "export class StreamHandle",
            );
            // Even on RED at HEAD, the class exists; we look for the
            // next() signature within its body.
            const streamHandleSlice =
                streamHandleStart >= 0
                    ? dtsText.slice(streamHandleStart, streamHandleStart + 4000)
                    : "";
            const nextSig = /next\([^)]*\)\s*:\s*[^;]+/m.exec(streamHandleSlice);
            expect(
                nextSig,
                "StreamHandle.next() signature MUST be findable in index.d.ts after PR-B regenerates it",
            ).not.toBeNull();

            // PRE-PR-B (RED): nextSig[0] contains `Buffer | null` and no
            // `Promise`. POST-PR-B (GREEN): contains `Promise<...>` (the
            // AsyncTask body). Asserting on the GREEN shape — un-skip
            // wave makes this PASS.
            expect(
                /Promise/.test(nextSig![0]),
                `post-PR-B index.d.ts must declare StreamHandle.next() as Promise-returning (the AsyncTask shape). Found: ${nextSig![0]}. \
RED at HEAD because next() is still SYNC \`Buffer | null\` per bindings/napi/src/lib.rs:2021.`,
            ).toBe(true);
        });

        it("types.ts atomically mirrors the StreamHandle.next() sync→async break (§3.5g — would-FAIL if index.d.ts updated alone)", () => {
            const typesTs = readWorkspaceFile("packages/engine/src/types.ts");
            // types.ts must exist by FREEZE (per §1.A.FROZEN item 10);
            // at HEAD it may or may not yet exist as the dedicated file
            // (could be a re-export). The pin tolerates HEAD shape but
            // asserts post-PR-B presence + Promise mirror.
            expect(
                typesTs,
                "packages/engine/src/types.ts MUST exist by G-CORE-10 (per §1.A.FROZEN item 10 — the JS public-API surface is enumerated)",
            ).not.toBeNull();

            const t = typesTs ?? "";
            // The §3.5g atomic-mirror obligation: if the .d.ts says
            // Promise, types.ts must too. We do NOT lock the exact
            // type name (StreamHandleNext, StreamChunk, etc.) — just
            // that the next() declaration in types.ts is Promise-shaped.
            const nextDecl = /next[^=]*=[^;]*Promise/.test(t) || /next\([^)]*\)\s*:\s*Promise/.test(t);
            expect(
                nextDecl,
                "post-PR-B packages/engine/src/types.ts MUST mirror the index.d.ts Promise shape for StreamHandle.next() (§3.5g cross-language rule-mirror; the WHOLE pin is the atomic Rust↔TS update obligation). Missing mirror means PR-B regenerated index.d.ts but forgot the TS-side consumer — the exact #1204 failure class.",
            ).toBe(true);
        });

        it("errors.generated.ts ErrorCode set mirrors any new G-CORE-10 ErrorCode mints atomically (§3.5g 4-surface mirror)", () => {
            const errsGen = readWorkspaceFile(
                "packages/engine/src/errors.generated.ts",
            );
            expect(
                errsGen,
                "packages/engine/src/errors.generated.ts MUST exist (existing §3.5g cross-language ErrorCode mirror surface)",
            ).not.toBeNull();

            // We do NOT enumerate which ErrorCodes G-CORE-10 might mint
            // (that is the implementer's R5 decision — perhaps
            // StreamCancelledDuringNext, or none). What we DO pin is
            // that IF any new variants are added Rust-side, they
            // mirror here atomically (§3.5g rule-mirror; the
            // CATALOG_VARIANT_COUNT discipline). Post-PR-B, the
            // implementer adds the variant on Rust side, regenerates
            // errors.generated.ts, and this pin's atomic-update arm
            // catches a forgotten regeneration as RED.
            //
            // RED at HEAD: this assertion fails ONLY when PR-B mints a
            // new variant Rust-side without regenerating TS — i.e. it
            // is the §3.5g rule-mirror reverse-direction guard.
            throw new Error(
                "RED-PHASE: un-skip at G-CORE-10 (PR-B #1203). The body \
to wire at un-skip: extract the ErrorCode union from \
errors.generated.ts; extract the ErrorCode enum variants from \
`crates/benten-errors/src/error_code.rs`; assert the two sets are \
byte-equal (post-rename). At PR-B time the implementer regenerates \
errors.generated.ts as part of the same PR (§3.5g rule-mirror); a \
forgotten regen → this arm fails (would-FAIL on missed atomic \
update). Pre-PR-B (HEAD): the sets already match (the existing \
errors.generated.ts is regenerated regularly), so the staged-pin is \
RED purely to enforce the un-skip-at-PR-B discipline.",
            );
        });
    },
);
